const WORD_LIST = [
  "KALEM", "ARABA", "DENIZ", "ELMA", "FINCAN", "GUNES", "HABER", "INSAN",
  "JAPON", "KABLO", "LIMON", "MASA", "NISAN", "OCAK", "PERDE", "RAPOR",
  "SABAH", "TABLO", "ULKER", "VATAN", "YAZAR", "ZEMIN", "BAHCE", "CADDE",
  "DOGAN", "EKRAN", "FENER", "GUMUS", "HAMAM", "IZMIR", "KARMA", "LAMBA",
  "MOTOR", "NOTER", "ORMAN", "PASTA", "RADAR", "SALON", "TARIM", "UZMAN",
  "VAPUR", "YATAK", "ZEKAT", "ASKERI", "BALIK", "CEMRE", "DOLAP", "EKMEK",
  "FATURA", "GEZGIN", "HALUK", "IRMAK", "JETON", "KASAP", "LOKUM", "MEYVE",
  "NEHIR", "OKYAN", "PAKET", "RESIM", "SINIF", "TAHTA", "UYGUR", "VULKAN",
  "YUMAK", "ZIRVE", "ADRES", "BORSA", "CUCUK", "DIVAN", "ERKEN", "FILIZ",
  "GOREV", "HILAL", "ISHAL", "JOKER", "KABUK", "LAHZA", "MASAL", "NIMET",
  "ODEON", "PAZAR", "RAFIK", "SIMIT", "TOPUZ", "UMRAN", "VAGON", "YAKUT",
  "ZAMAN", "ATLAS", "BURAK", "CORAP", "DERGI", "EDIP", "FIDAN", "GURUR",
  "HAYAT", "IDEAL", "KABUL", "LIMIT", "MIRAS", "NEFES", "OMLET", "PLAKA",
  "REHIN", "SUPER", "TUZAK", "USARE", "VELUT", "YURDU", "ZEMIN", "AKTIF",
  "BELGE", "CINAR", "DEVIR", "EBADI", "FABUL", "GUZEL", "HASTA", "IPLIK",
  "KAZAN", "LISAN", "MAKAM", "NAMUS", "OLCEK", "PANEL", "RESUL", "SIGOR",
  "TALEP", "USTAD", "VIZOR", "YAZIM", "ZULUF"
];

const TURKISH_ALPHABET = "ABCDEFGHIJKLMNOPRSTUVYZÇĞİÖŞÜ".split('');
